version: "3"

services: 
  two-factor-api:
    restart: always
    # if docker file is in another folder set context: ./server
    # build this container with my Dockerfile
    # but if i have a dockerfile elsewhere or with a custom name
    # declare it at the dockerfile section
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      # do not try overwrite this folder app/node_modules
      # in the container with the one in our directory
      - /app/node_modules
      # map current folder/directory to /app inside the container
      # This is a must for a development environment in order to update the container whenever a change to the source code is made. Without this, you would have to rebuild the image each time you make a change to the code.
      - .:/app
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
    environment: 
      - MONGO_URI=mongodb://admin:password@mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017" 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=two-factor
    volumes: 
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123456
        
volumes:
  mongo-data:
    driver: local
            

 


